# Generated by Django 3.0.7 on 2020-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0004_auto_20200620_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='groups',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='groups.groupModel'),
        ),
    ]
