# Generated by Django 3.0.7 on 2020-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='groups',
            field=models.ManyToManyField(to='groups.groupModel'),
        ),
    ]
