# Generated by Django 3.0.7 on 2020-06-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0003_auto_20200620_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='groups',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupModel'),
        ),
    ]
